print('=====DESAFIO 10=====')

print('BEM-VINDO A MINHA TABUADA')

n = int(input('Digite um número por favor:'))
print('-'*12)
#Primeiro jeito de se fazer
#print('{} X 1 ='.format(n), n * 1)
#print('{} X 2 ='.format(n), n * 2)
#print('{} X 3 ='.format(n), n * 3)
#print('{} X 4 ='.format(n), n * 4)
#print('{} X 5 ='.format(n), n * 5)
#print('{} X 6 ='.format(n), n * 6)
#print('{} X 7 ='.format(n), n * 7)
#print('{} X 8 ='.format(n), n * 8)
#print('{} X 9 ='.format(n), n * 9)
#print('{} X 10 ='.format(n), n * 10)

#Segundo jeito de se fazer
print('{} x {:2} = {}'.format(n,1,n*1))
print('{} x {:2} = {}'.format(n,2,n*2))
print('{} x {:2} = {}'.format(n,3,n*3))
print('{} x {:2} = {}'.format(n,4,n*4))
print('{} x {:2} = {}'.format(n,5,n*5))
print('{} x {:2} = {}'.format(n,6,n*6))
print('{} x {:2} = {}'.format(n,7,n*7))
print('{} x {:2} = {}'.format(n,8,n*8))
print('{} x {:2} = {}'.format(n,9,n*9))
print('{} x {:2} = {}'.format(n,10,n*10))
print('-'*12)
